export const STATUS_PRESET_COLORS = [
  { value: '#22c55e', labelKey: 'cfg.status.color.green' },
  { value: '#3b82f6', labelKey: 'cfg.status.color.blue' },
  { value: '#f59e0b', labelKey: 'cfg.status.color.orange' },
  { value: '#ef4444', labelKey: 'cfg.status.color.red' },
  { value: '#8b5cf6', labelKey: 'cfg.status.color.purple' },
  { value: '#06b6d4', labelKey: 'cfg.status.color.cyan' },
  { value: '#ec4899', labelKey: 'cfg.status.color.pink' },
  { value: '#6b7280', labelKey: 'cfg.status.color.gray' },
  { value: '#14b8a6', labelKey: 'cfg.status.color.teal' },
  { value: '#f97316', labelKey: 'cfg.status.color.deep_orange' },
  { value: '#84cc16', labelKey: 'cfg.status.color.lime' },
  { value: '#a855f7', labelKey: 'cfg.status.color.bright_purple' },
  { value: '#0ea5e9', labelKey: 'cfg.status.color.sky_blue' },
  { value: '#f43f5e', labelKey: 'cfg.status.color.rose' },
  { value: '#64748b', labelKey: 'cfg.status.color.slate' },
];
